---
all:
  children:
    rabbitmq_cluster:
      hosts:
        rabbitmq-01:
          ansible_host: 192.168.1.101
          rabbitmq_node_name: rabbit@rabbitmq-01
          rabbitmq_node_type: disc
        rabbitmq-02:
          ansible_host: 192.168.1.102
          rabbitmq_node_name: rabbit@rabbitmq-02
          rabbitmq_node_type: disc
        rabbitmq-03:
          ansible_host: 192.168.1.103
          rabbitmq_node_name: rabbit@rabbitmq-03
          rabbitmq_node_type: disc
      vars:
        rabbitmq_cluster_master: rabbitmq-01
