---
all:
  children:
    rabbitmq_cluster:
      hosts:
        rabbitmq-stg-01:
          ansible_host: 10.0.1.101
          rabbitmq_node_name: rabbit@rabbitmq-stg-01
          rabbitmq_node_type: disc
        rabbitmq-stg-02:
          ansible_host: 10.0.1.102
          rabbitmq_node_name: rabbit@rabbitmq-stg-02
          rabbitmq_node_type: disc
        rabbitmq-stg-03:
          ansible_host: 10.0.1.103
          rabbitmq_node_name: rabbit@rabbitmq-stg-03
          rabbitmq_node_type: disc
      vars:
        rabbitmq_cluster_master: rabbitmq-stg-01
